const axios = require('axios');
const config = require('../config');
const { applyFont } = require('../lib/fonts');

module.exports = async (sock, sender, args, msg, { safeSendMessage, sendReaction }) => {
    if (!args.length) {
        await safeSendMessage(sender, { 
            text: applyFont('❌ *Please provide prompt!*\nExample: .flux beautiful landscape') 
        });
        return;
    }
    
    const prompt = args.join(' ');
    
    try {
        await sendReaction(msg, '🎨');
        await safeSendMessage(sender, { text: applyFont('🎨 *Generating AI image...*') });
        
        const response = await axios.get(`https://api.bk9.dev/ai/fluximg?q=${encodeURIComponent(prompt)}`, {
            timeout: 30000
        });
        
        if (response.data.status && response.data.result) {
            await safeSendMessage(sender, {
                image: { url: response.data.result },
                caption: applyFont(`*╭━━━〔 🐢 𝙰𝙸 𝙸𝙼𝙰𝙶𝙴 🐢 〕━━━┈⊷*
*┃🐢│ 𝙿𝚁𝙾𝙼𝙿𝚃 :❯ ${prompt}*
*╰━━━━━━━━━━━━━━━┈⊷*

🎨 *Generated by Sila MD*`)
            });
            await sendReaction(msg, '✨');
        } else {
            await safeSendMessage(sender, { 
                text: applyFont('❌ *Failed to generate image!*\nPlease try another prompt.') 
            });
        }
    } catch (error) {
        await safeSendMessage(sender, { 
            text: applyFont('❌ *AI service error!*\nPlease try again later.') 
        });
    }
};